<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="AwesomeAssertions" />
    <Using Include="Testcontainers.MsSql" />
    <Using Include="Microsoft.AspNetCore.Mvc.Testing" />
    <Using Include="Respawn" />
    <Using Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Chat.Api\Chat.Api.csproj" />
    <ProjectReference Include="..\..\src\Chat.Infrastructure\Chat.Infrastructure.csproj" />
  </ItemGroup>

</Project>