<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Chat.Application\Chat.Application.csproj" />
  </ItemGroup>
</Project>
